"""update_user_attempt_relationships

Revision ID: 03bfaf374b78
Revises: a5fb82dc96c4
Create Date: 2025-01-19 10:47:51.910771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bfaf374b78'
down_revision: Union[str, None] = 'a5fb82dc96c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attempts', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_user_attempts_created_at', 'user_attempts', ['created_at'], unique=False)
    op.create_index('idx_user_attempts_user_chapter', 'user_attempts', ['user_id', 'chapter'], unique=False)
    op.create_foreign_key(None, 'user_attempts', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_attempts', 'question_id_old')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attempts', sa.Column('question_id_old', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_attempts', type_='foreignkey')
    op.drop_index('idx_user_attempts_user_chapter', table_name='user_attempts')
    op.drop_index('idx_user_attempts_created_at', table_name='user_attempts')
    op.alter_column('user_attempts', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###