"""Add is_used column to VerificationToken

Revision ID: 16b6035a5059
Revises: c5e1641f58f5
Create Date: 2024-12-31 19:31:49.900867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b6035a5059'
down_revision: Union[str, None] = 'c5e1641f58f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('is_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_tokens', 'is_used')
    # ### end Alembic commands ###