"""add feedback column to user_attempts

Revision ID: 8e5f77bdfe15
Revises: d0caf7350242
Create Date: 2025-01-01 14:45:25.123858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e5f77bdfe15'
down_revision: Union[str, None] = 'd0caf7350242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attempts', sa.Column('feedback', sa.String(), nullable=True))
    op.drop_index('ix_user_attempts_board', table_name='user_attempts')
    op.drop_index('ix_user_attempts_chapter', table_name='user_attempts')
    op.drop_index('ix_user_attempts_question_id', table_name='user_attempts')
    op.drop_index('ix_user_attempts_subject', table_name='user_attempts')
    op.drop_column('user_attempts', 'attempts')
    op.drop_column('user_attempts', 'updated_at')
    op.drop_column('user_attempts', 'last_attempt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attempts', sa.Column('last_attempt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_attempts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_attempts', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_user_attempts_subject', 'user_attempts', ['subject'], unique=False)
    op.create_index('ix_user_attempts_question_id', 'user_attempts', ['question_id'], unique=False)
    op.create_index('ix_user_attempts_chapter', 'user_attempts', ['chapter'], unique=False)
    op.create_index('ix_user_attempts_board', 'user_attempts', ['board'], unique=False)
    op.drop_column('user_attempts', 'feedback')
    # ### end Alembic commands ###