"""Create questions table

Revision ID: be7193b373a7
Revises: ad4b223c336d
Create Date: 2025-01-13 10:55:55.685906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7193b373a7'
down_revision: Union[str, None] = 'ad4b223c336d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('human_readable_id', sa.String(), nullable=False),
    sa.Column('file_source', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('class_level', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_readable_id')
    )
    op.create_index('idx_questions_board_class_subject_chapter', 'questions', ['board', 'class_level', 'subject', 'chapter'], unique=False)
    op.create_index('idx_questions_category', 'questions', ['category'], unique=False)
    op.create_index('idx_questions_human_readable_id', 'questions', ['human_readable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_questions_human_readable_id', table_name='questions')
    op.drop_index('idx_questions_category', table_name='questions')
    op.drop_index('idx_questions_board_class_subject_chapter', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###